# Generated by Django 3.0.2 on 2020-02-17 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameMechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_tags', models.ManyToManyField(to='boardgames.BoardGameTag')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('min_players', models.IntegerField(null=True)),
                ('max_players', models.IntegerField(null=True)),
                ('best_with', models.IntegerField(null=True)),
                ('len_m', models.IntegerField(null=True)),
                ('min_len_m', models.IntegerField(null=True)),
                ('max_len_m', models.IntegerField(null=True)),
                ('average', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('bayes_average', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('categories', models.ManyToManyField(to='boardgames.BoardGameCategory')),
                ('mechanics', models.ManyToManyField(to='boardgames.BoardGameMechanic')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameExpansion',
            fields=[
                ('boardgame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boardgames.BoardGame')),
                ('base_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='boardgames.BoardGame')),
            ],
            bases=('boardgames.boardgame',),
        ),
        migrations.CreateModel(
            name='PersonalBoardGameExpansion',
            fields=[
                ('boardgameexpansion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boardgames.BoardGameExpansion')),
                ('expansion_tags', models.ManyToManyField(to='boardgames.BoardGameTag')),
            ],
            bases=('boardgames.boardgameexpansion',),
        ),
    ]
