# Generated by Django 3.0.3 on 2020-02-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_auto_20200219_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('start_player', models.BooleanField()),
                ('new_player', models.BooleanField()),
                ('team', models.IntegerField()),
                ('winner', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='play',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bgg_name',
        ),
        migrations.AddField(
            model_name='play',
            name='ignore',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='play_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='bgg_stats_uuid',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='bgg_username',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='bgstats_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='boardgames.BoardGame'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='PlayerResult',
        ),
        migrations.AddField(
            model_name='playerscore',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_session', to='boardgames.Play'),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='boardgames.Player'),
        ),
    ]
