# Generated by Django 3.0.3 on 2020-02-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_auto_20200220_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='bgg_stats_uuid',
            new_name='bgstats_uuid',
        ),
    ]
