# Generated by Django 3.0.3 on 2020-02-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0004_auto_20200220_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='game_uuid',
            field=models.CharField(default=None, max_length=36, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='play',
            name='ignore',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='play_date',
            field=models.DateTimeField(null=True),
        ),
    ]
