# Generated by Django 3.0.3 on 2020-02-20 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0005_auto_20200220_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='bgstats_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='cooperative',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='highest_wins',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='no_points',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='uses_teams',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='seat_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='play',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='boardgames.BoardGame'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='new_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='boardgames.Play'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='boardgames.Player'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='start_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
