# Generated by Django 3.0.3 on 2020-02-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0008_auto_20200220_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='comments',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='difficulty',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='role',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='team',
            field=models.IntegerField(null=True),
        ),
    ]
